### ISSUE TITLE
ImportError: No module named dircast.cli

### ISSUE THREAD

**Issue by maphew** [calpaterson/dircast#1]
_Maybe this scratches your personal itch and getting started issues like this aren't interesting to you. If that's the case feel free to close and move on. However if you are interested, it doesn't work out of the box on Windows._ 

Clone to Desktop (Windows 7 Github Desktop),

```
cd d:\code\dircast
pip install --editable .
```

Install stuff happens

```
[py27] D:\code\dircast
> dircast
Traceback (most recent call last):
  File "C:\Python27\Scripts\dircast-script.py", line 9, in <module>
    load_entry_point('dircast==0.0', 'console_scripts', 'dircast')()
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2470, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2184, in load
    ['__name__'])
ImportError: No module named dircast.cli
```

**Comment by maphew** [comment]
ahh, progress! There's no `./dircast/__init__.py`. Add that (empty file) and we move on to other errors about missing dependencies: **pathlib**, **libmagic**

Getting pathlib is straightforward, just pip install. Libmagic on Windows is a bit more work, `pip install python-magic` was already done when installing dircast, but it must be followed by ensuring [dependent DLL files](https://github.com/ahupp/python-magic#dependencies) are in PATH.

...and then we hit a thicker wall, `WindowsError: [Error 193] %1 is not a valid Win32 application`. The python-magic readme says this is when using 64bit python and 32bit DLLs. I'll have to change my python install and come back later.

**Comment by maphew** [comment]
Confirm working with 32bit python 2.7 install on Windows -- at least to the point of emitting usage message. I haven't tried to create a feed files yet.

**Comment by calpaterson** [comment]
Thanks for looking into this.  I didn't think of Windows users when I wrote this
